/*
 * traQ v3
 *
 * traQ v3 API
 *
 * The version of the OpenAPI document: 3.0
 *
 * Generated by: https://openapi-generator.tech
 */

/// ChannelList : GET /channelsレスポンス

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ChannelList {
    /// パブリックチャンネルの配列
    #[serde(rename = "public")]
    pub public: Vec<crate::models::Channel>,
    /// ダイレクトメッセージチャンネルの配列
    #[serde(rename = "dm", default)]
    pub dm: Vec<crate::models::DmChannel>,
}

impl ChannelList {
    /// GET /channelsレスポンス
    pub fn new(
        public: Vec<crate::models::Channel>,
        dm: Vec<crate::models::DmChannel>,
    ) -> ChannelList {
        ChannelList { public, dm }
    }
}
