/*
 * traQ v3
 *
 * traQ v3 API
 *
 * The version of the OpenAPI document: 3.0
 *
 * Generated by: https://openapi-generator.tech
 */

/// Channel : チャンネル

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Channel {
    /// チャンネルUUID
    #[serde(rename = "id")]
    pub id: String,
    /// 親チャンネルUUID
    #[serde(rename = "parentId")]
    pub parent_id: Option<String>,
    /// チャンネルがアーカイブされているかどうか
    #[serde(rename = "archived")]
    pub archived: bool,
    /// 強制通知チャンネルかどうか
    #[serde(rename = "force")]
    pub force: bool,
    /// チャンネルトピック
    #[serde(rename = "topic")]
    pub topic: String,
    /// チャンネル名
    #[serde(rename = "name")]
    pub name: String,
    /// 子チャンネルのUUID配列
    #[serde(rename = "children")]
    pub children: Vec<String>,
}

impl Channel {
    /// チャンネル
    pub fn new(
        id: String,
        parent_id: Option<String>,
        archived: bool,
        force: bool,
        topic: String,
        name: String,
        children: Vec<String>,
    ) -> Channel {
        Channel {
            id,
            parent_id,
            archived,
            force,
            topic,
            name,
            children,
        }
    }
}
