/*
 * traQ v3
 *
 * traQ v3 API
 *
 * The version of the OpenAPI document: 3.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// ChannelSubscribeLevel : チャンネル購読レベル 0：無し 1：未読管理 2：未読管理+通知

/// チャンネル購読レベル 0：無し 1：未読管理 2：未読管理+通知
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ChannelSubscribeLevel {
    #[serde(rename = "0")]
    none,
    #[serde(rename = "1")]
    subscribed,
    #[serde(rename = "2")]
    notified,

}




