/*
 * traQ v3
 *
 * traQ v3 API
 *
 * The version of the OpenAPI document: 3.0
 *
 * Generated by: https://openapi-generator.tech
 */

/// ChildCreatedEvent : 子チャンネル作成イベント

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ChildCreatedEvent {
    /// 作成者UUID
    #[serde(rename = "userId")]
    pub user_id: String,
    /// チャンネルUUID
    #[serde(rename = "channelId")]
    pub channel_id: String,
}

impl ChildCreatedEvent {
    /// 子チャンネル作成イベント
    pub fn new(user_id: String, channel_id: String) -> ChildCreatedEvent {
        ChildCreatedEvent {
            user_id,
            channel_id,
        }
    }
}
