/*
 * traQ v3
 *
 * traQ v3 API
 *
 * The version of the OpenAPI document: 3.0
 *
 * Generated by: https://openapi-generator.tech
 */

/// ClipFolder : クリップフォルダ情報

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ClipFolder {
    /// フォルダUUID
    #[serde(rename = "id")]
    pub id: String,
    /// フォルダ名
    #[serde(rename = "name")]
    pub name: String,
    /// 作成日時
    #[serde(rename = "createdAt")]
    pub created_at: String,
    /// フォルダ所有者UUID
    #[serde(rename = "ownerId")]
    pub owner_id: String,
    /// 説明
    #[serde(rename = "description")]
    pub description: String,
}

impl ClipFolder {
    /// クリップフォルダ情報
    pub fn new(
        id: String,
        name: String,
        created_at: String,
        owner_id: String,
        description: String,
    ) -> ClipFolder {
        ClipFolder {
            id,
            name,
            created_at,
            owner_id,
            description,
        }
    }
}
