/*
 * traQ v3
 *
 * traQ v3 API
 *
 * The version of the OpenAPI document: 3.0
 *
 * Generated by: https://openapi-generator.tech
 */

/// FileInfo : ファイル情報

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct FileInfo {
    /// ファイルUUID
    #[serde(rename = "id")]
    pub id: String,
    /// ファイル名
    #[serde(rename = "name")]
    pub name: String,
    /// MIMEタイプ
    #[serde(rename = "mime")]
    pub mime: String,
    /// ファイルサイズ
    #[serde(rename = "size")]
    pub size: i64,
    /// MD5ハッシュ
    #[serde(rename = "md5")]
    pub md5: String,
    /// アップロード日時
    #[serde(rename = "createdAt")]
    pub created_at: String,
    #[serde(rename = "thumbnail")]
    pub thumbnail: Option<crate::models::FileInfoThumbnail>,
    /// 属しているチャンネルUUID
    #[serde(rename = "channelId")]
    pub channel_id: Option<String>,
    /// アップロード者UUID
    #[serde(rename = "uploaderId")]
    pub uploader_id: Option<String>,
}

impl FileInfo {
    /// ファイル情報
    pub fn new(
        id: String,
        name: String,
        mime: String,
        size: i64,
        md5: String,
        created_at: String,
        thumbnail: Option<crate::models::FileInfoThumbnail>,
        channel_id: Option<String>,
        uploader_id: Option<String>,
    ) -> FileInfo {
        FileInfo {
            id,
            name,
            mime,
            size,
            md5,
            created_at,
            thumbnail,
            channel_id,
            uploader_id,
        }
    }
}
