/*
 * traQ v3
 *
 * traQ v3 API
 *
 * The version of the OpenAPI document: 3.0
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct InlineObject {
    /// スタンプ画像(1MBまでのpng, jpeg, gif)
    #[serde(rename = "file")]
    pub file: std::path::PathBuf,
}

impl InlineObject {
    pub fn new(file: std::path::PathBuf) -> InlineObject {
        InlineObject { file }
    }
}
