/*
 * traQ v3
 *
 * traQ v3 API
 *
 * The version of the OpenAPI document: 3.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// LoginSession : ログインセッション情報



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct LoginSession {
    /// セッションUUID
    #[serde(rename = "id")]
    pub id: String,
    /// 発行日時
    #[serde(rename = "issuedAt")]
    pub issued_at: String,
}

impl LoginSession {
    /// ログインセッション情報
    pub fn new(id: String, issued_at: String) -> LoginSession {
        LoginSession {
            id,
            issued_at,
        }
    }
}


