/*
 * traQ v3
 *
 * traQ v3 API
 *
 * The version of the OpenAPI document: 3.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// Message : メッセージ



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Message {
    /// メッセージUUID
    #[serde(rename = "id")]
    pub id: String,
    /// 投稿者UUID
    #[serde(rename = "userId")]
    pub user_id: String,
    /// チャンネルUUID
    #[serde(rename = "channelId")]
    pub channel_id: String,
    /// メッセージ本文
    #[serde(rename = "content")]
    pub content: String,
    /// 投稿日時
    #[serde(rename = "createdAt")]
    pub created_at: String,
    /// 編集日時
    #[serde(rename = "updatedAt")]
    pub updated_at: String,
    /// ピン留めされているかどうか
    #[serde(rename = "pinned")]
    pub pinned: bool,
    /// 押されているスタンプの配列
    #[serde(rename = "stamps")]
    pub stamps: Vec<crate::models::MessageStamp>,
    /// スレッドUUID
    #[serde(rename = "threadId")]
    pub thread_id: Option<String>,
}

impl Message {
    /// メッセージ
    pub fn new(id: String, user_id: String, channel_id: String, content: String, created_at: String, updated_at: String, pinned: bool, stamps: Vec<crate::models::MessageStamp>, thread_id: Option<String>) -> Message {
        Message {
            id,
            user_id,
            channel_id,
            content,
            created_at,
            updated_at,
            pinned,
            stamps,
            thread_id,
        }
    }
}


