/*
 * traQ v3
 *
 * traQ v3 API
 *
 * The version of the OpenAPI document: 3.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// NameChangedEvent : チャンネル名変更イベント



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct NameChangedEvent {
    /// 変更者UUID
    #[serde(rename = "userId")]
    pub user_id: String,
    /// 変更前チャンネル名
    #[serde(rename = "before")]
    pub before: String,
    /// 変更後チャンネル名
    #[serde(rename = "after")]
    pub after: String,
}

impl NameChangedEvent {
    /// チャンネル名変更イベント
    pub fn new(user_id: String, before: String, after: String) -> NameChangedEvent {
        NameChangedEvent {
            user_id,
            before,
            after,
        }
    }
}


