/*
 * traQ v3
 *
 * traQ v3 API
 *
 * The version of the OpenAPI document: 3.0
 *
 * Generated by: https://openapi-generator.tech
 */

/// OgpMedia : OGPに含まれる画像の情報

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct OgpMedia {
    #[serde(rename = "url", skip_serializing_if = "Option::is_none")]
    pub url: Option<String>,
    #[serde(rename = "secureUrl", skip_serializing_if = "Option::is_none")]
    pub secure_url: Option<String>,
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub _type: Option<String>,
    #[serde(rename = "width", skip_serializing_if = "Option::is_none")]
    pub width: Option<i32>,
    #[serde(rename = "height", skip_serializing_if = "Option::is_none")]
    pub height: Option<i32>,
}

impl OgpMedia {
    /// OGPに含まれる画像の情報
    pub fn new() -> OgpMedia {
        OgpMedia {
            url: None,
            secure_url: None,
            _type: None,
            width: None,
            height: None,
        }
    }
}
