/*
 * traQ v3
 *
 * traQ v3 API
 *
 * The version of the OpenAPI document: 3.0
 *
 * Generated by: https://openapi-generator.tech
 */

/// Pin : ピン情報(メッセージ本体付き)

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Pin {
    /// ピン留めしたユーザーUUID
    #[serde(rename = "userId")]
    pub user_id: String,
    /// ピン留めされた日時
    #[serde(rename = "pinnedAt")]
    pub pinned_at: String,
    #[serde(rename = "message")]
    pub message: crate::models::Message,
}

impl Pin {
    /// ピン情報(メッセージ本体付き)
    pub fn new(user_id: String, pinned_at: String, message: crate::models::Message) -> Pin {
        Pin {
            user_id,
            pinned_at,
            message,
        }
    }
}
