/*
 * traQ v3
 *
 * traQ v3 API
 *
 * The version of the OpenAPI document: 3.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// PostChannelRequest : チャンネル作成リクエスト



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct PostChannelRequest {
    /// チャンネル名
    #[serde(rename = "name")]
    pub name: String,
    /// 親チャンネルのUUID ルートに作成する場合はnullを指定
    #[serde(rename = "parent")]
    pub parent: Option<String>,
}

impl PostChannelRequest {
    /// チャンネル作成リクエスト
    pub fn new(name: String, parent: Option<String>) -> PostChannelRequest {
        PostChannelRequest {
            name,
            parent,
        }
    }
}


