/*
 * traQ v3
 *
 * traQ v3 API
 *
 * The version of the OpenAPI document: 3.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// PostBotActionLeaveRequest : BOTチャンネル退出リクエスト



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct PostBotActionLeaveRequest {
    /// チャンネルUUID
    #[serde(rename = "channelId")]
    pub channel_id: String,
}

impl PostBotActionLeaveRequest {
    /// BOTチャンネル退出リクエスト
    pub fn new(channel_id: String) -> PostBotActionLeaveRequest {
        PostBotActionLeaveRequest {
            channel_id,
        }
    }
}


