/*
 * traQ v3
 *
 * traQ v3 API
 *
 * The version of the OpenAPI document: 3.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// PostStampRequest : スタンプ作成リクエスト



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct PostStampRequest {
    /// スタンプ名
    #[serde(rename = "name")]
    pub name: String,
    /// スタンプ画像(1MBまでのpng, jpeg, gif)
    #[serde(rename = "file")]
    pub file: std::path::PathBuf,
}

impl PostStampRequest {
    /// スタンプ作成リクエスト
    pub fn new(name: String, file: std::path::PathBuf) -> PostStampRequest {
        PostStampRequest {
            name,
            file,
        }
    }
}


