/*
 * traQ v3
 *
 * traQ v3 API
 *
 * The version of the OpenAPI document: 3.0
 *
 * Generated by: https://openapi-generator.tech
 */

/// PostBotRequest : BOT作成リクエスト

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct PostBotRequest {
    /// BOTユーザーID 自動的に接頭辞\"BOT_\"が付与されます
    #[serde(rename = "name")]
    pub name: String,
    /// BOTユーザー表示名
    #[serde(rename = "displayName")]
    pub display_name: String,
    /// BOTの説明
    #[serde(rename = "description")]
    pub description: String,
    /// BOTサーバーエンドポイント
    #[serde(rename = "endpoint")]
    pub endpoint: String,
}

impl PostBotRequest {
    /// BOT作成リクエスト
    pub fn new(
        name: String,
        display_name: String,
        description: String,
        endpoint: String,
    ) -> PostBotRequest {
        PostBotRequest {
            name,
            display_name,
            description,
            endpoint,
        }
    }
}
