/*
 * traQ v3
 *
 * traQ v3 API
 *
 * The version of the OpenAPI document: 3.0
 *
 * Generated by: https://openapi-generator.tech
 */

/// PostOAuth2Revoke : POST /oauth2/revoke 用リクエストボディ

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct PostOAuth2Revoke {
    /// 無効化するOAuth2トークンまたはOAuth2リフレッシュトークン
    #[serde(rename = "token")]
    pub token: String,
}

impl PostOAuth2Revoke {
    /// POST /oauth2/revoke 用リクエストボディ
    pub fn new(token: String) -> PostOAuth2Revoke {
        PostOAuth2Revoke { token }
    }
}
