/*
 * traQ v3
 *
 * traQ v3 API
 *
 * The version of the OpenAPI document: 3.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// StampPalette : スタンプパレット情報



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct StampPalette {
    /// スタンプパレットUUID
    #[serde(rename = "id")]
    pub id: String,
    /// パレット名
    #[serde(rename = "name")]
    pub name: String,
    /// パレット内のスタンプのUUID配列
    #[serde(rename = "stamps")]
    pub stamps: Vec<String>,
    /// 作成者UUID
    #[serde(rename = "creatorId")]
    pub creator_id: String,
    /// パレット作成日時
    #[serde(rename = "createdAt")]
    pub created_at: String,
    /// パレット更新日時
    #[serde(rename = "updatedAt")]
    pub updated_at: String,
    /// パレット説明
    #[serde(rename = "description")]
    pub description: String,
}

impl StampPalette {
    /// スタンプパレット情報
    pub fn new(id: String, name: String, stamps: Vec<String>, creator_id: String, created_at: String, updated_at: String, description: String) -> StampPalette {
        StampPalette {
            id,
            name,
            stamps,
            creator_id,
            created_at,
            updated_at,
            description,
        }
    }
}


