/*
 * traQ v3
 *
 * traQ v3 API
 *
 * The version of the OpenAPI document: 3.0
 *
 * Generated by: https://openapi-generator.tech
 */

/// SubscribersChangedEvent : 購読者変更イベント

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct SubscribersChangedEvent {
    /// 変更者UUID
    #[serde(rename = "userId")]
    pub user_id: String,
    /// オンにされたユーザーのUUID配列
    #[serde(rename = "on")]
    pub on: Vec<String>,
    /// オフにされたユーザーのUUID配列
    #[serde(rename = "off")]
    pub off: Vec<String>,
}

impl SubscribersChangedEvent {
    /// 購読者変更イベント
    pub fn new(user_id: String, on: Vec<String>, off: Vec<String>) -> SubscribersChangedEvent {
        SubscribersChangedEvent { user_id, on, off }
    }
}
