/*
 * traQ v3
 *
 * traQ v3 API
 *
 * The version of the OpenAPI document: 3.0
 *
 * Generated by: https://openapi-generator.tech
 */

/// Tag : タグ情報

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Tag {
    /// タグUUID
    #[serde(rename = "id")]
    pub id: String,
    /// タグ文字列
    #[serde(rename = "tag")]
    pub tag: String,
    /// タグがつけられているユーザーのUUID配列
    #[serde(rename = "users")]
    pub users: Vec<String>,
}

impl Tag {
    /// タグ情報
    pub fn new(id: String, tag: String, users: Vec<String>) -> Tag {
        Tag { id, tag, users }
    }
}
