/*
 * traQ v3
 *
 * traQ v3 API
 *
 * The version of the OpenAPI document: 3.0
 *
 * Generated by: https://openapi-generator.tech
 */

/// TopicChangedEvent : トピック変更イベント

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct TopicChangedEvent {
    /// 変更者UUID
    #[serde(rename = "userId")]
    pub user_id: String,
    /// 変更前トピック
    #[serde(rename = "before")]
    pub before: String,
    /// 変更後トピック
    #[serde(rename = "after")]
    pub after: String,
}

impl TopicChangedEvent {
    /// トピック変更イベント
    pub fn new(user_id: String, before: String, after: String) -> TopicChangedEvent {
        TopicChangedEvent {
            user_id,
            before,
            after,
        }
    }
}
