/*
 * traQ v3
 *
 * traQ v3 API
 *
 * The version of the OpenAPI document: 3.0
 *
 * Generated by: https://openapi-generator.tech
 */

/// UserGroup : ユーザーグループ

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct UserGroup {
    /// グループUUID
    #[serde(rename = "id")]
    pub id: String,
    /// グループ名
    #[serde(rename = "name")]
    pub name: String,
    /// グループ説明
    #[serde(rename = "description")]
    pub description: String,
    /// グループタイプ
    #[serde(rename = "type")]
    pub _type: String,
    /// グループメンバーの配列
    #[serde(rename = "members")]
    pub members: Vec<crate::models::UserGroupMember>,
    /// 作成日時
    #[serde(rename = "createdAt")]
    pub created_at: String,
    /// 更新日時
    #[serde(rename = "updatedAt")]
    pub updated_at: String,
    /// グループ管理者のUUIDの配列
    #[serde(rename = "admins")]
    pub admins: Vec<String>,
}

impl UserGroup {
    /// ユーザーグループ
    pub fn new(
        id: String,
        name: String,
        description: String,
        _type: String,
        members: Vec<crate::models::UserGroupMember>,
        created_at: String,
        updated_at: String,
        admins: Vec<String>,
    ) -> UserGroup {
        UserGroup {
            id,
            name,
            description,
            _type,
            members,
            created_at,
            updated_at,
            admins,
        }
    }
}
