/*
 * traQ v3
 *
 * traQ v3 API
 *
 * The version of the OpenAPI document: 3.0
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct VersionFlags {
    /// 有効な外部ログインプロバイダ
    #[serde(rename = "externalLogin")]
    pub external_login: Vec<String>,
}

impl VersionFlags {
    pub fn new(external_login: Vec<String>) -> VersionFlags {
        VersionFlags { external_login }
    }
}
