/*
 * traQ v3
 *
 * traQ v3 API
 *
 * The version of the OpenAPI document: 3.0
 *
 * Generated by: https://openapi-generator.tech
 */

/// VisibilityChangedEvent : チャンネル可視状態変更イベント

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct VisibilityChangedEvent {
    /// 変更者UUID
    #[serde(rename = "userId")]
    pub user_id: String,
    /// 変更後可視状態
    #[serde(rename = "visibility")]
    pub visibility: bool,
}

impl VisibilityChangedEvent {
    /// チャンネル可視状態変更イベント
    pub fn new(user_id: String, visibility: bool) -> VisibilityChangedEvent {
        VisibilityChangedEvent {
            user_id,
            visibility,
        }
    }
}
