/*
 * traQ v3
 *
 * traQ v3 API
 *
 * The version of the OpenAPI document: 3.0
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct WebRtcUserStateSessions {
    /// 状態
    #[serde(rename = "state")]
    pub state: String,
    /// セッションID
    #[serde(rename = "sessionId")]
    pub session_id: String,
}

impl WebRtcUserStateSessions {
    pub fn new(state: String, session_id: String) -> WebRtcUserStateSessions {
        WebRtcUserStateSessions { state, session_id }
    }
}
